MODULE CUDA_KERNELS

	USE CUDAFOR

	IMPLICIT NONE

    CONTAINS

    ATTRIBUTES (GLOBAL) SUBROUTINE boundary_x(A,imax,jmax)
        REAL(KIND=8), DEVICE, DIMENSION(*) :: A
        INTEGER(KIND=4), VALUE :: imax, jmax

        INTEGER(KIND=4) :: i, j

        j = blockDim%y * (blockIdx%y-1) + threadIdx%y
        i = blockDim%x * (blockIdx%x-1) + threadIdx%x

        IF(j == 1 .and. i <= imax+2) THEN
            A((j-1)*(imax+2) + i) = 0.0_8
        END IF

        IF(j == jmax+2 .and. i <= imax+2) THEN
            A((j-1)*(imax+2) + i) = 0.0_8
        END IF

    END SUBROUTINE boundary_x

    ATTRIBUTES (GLOBAL) SUBROUTINE boundary_y(A,imax,jmax,pi)
        REAL(KIND=8), DEVICE, DIMENSION(*) :: A
        INTEGER(KIND=4), VALUE :: imax, jmax
        REAL(KIND=8), VALUE :: pi

        INTEGER(KIND=4) :: i, j

        j = blockDim%y * (blockIdx%y-1) + threadIdx%y
        i = blockDim%x * (blockIdx%x-1) + threadIdx%x

        IF(i == 1 .and. j <= jmax+2) THEN
            A((j-1)*(imax+2) + i)   = sin(pi * j/(jmax+2))
        END IF

        IF(i == imax+2 .and. j <= jmax+2) THEN
            A((j-1)*(imax+2) + i) = sin(pi * j/(jmax+2)) * exp(-pi)
        END IF

    END SUBROUTINE boundary_y

    ATTRIBUTES (DEVICE) SUBROUTINE cuda_reduction_max(sharedReal8, reduction_res, input_value)
        REAL(KIND=8), DIMENSION(0:*) :: sharedReal8
        REAL(KIND=8), DIMENSION(*), DEVICE :: reduction_res
        REAL(KIND=8), INTENT(IN) :: input_value

        INTEGER(KIND=4) :: i1
        INTEGER(KIND=4) :: threadID

        threadID = (threadIdx%y-1)*blockDim%x + (threadIdx%x - 1)
        i1 = ishft(blockDim%x*blockDim%y,-1)

        CALL syncthreads()

        sharedReal8(threadID) = input_value

        DO WHILE (i1 > 0 )
            CALL syncthreads()
            IF (threadID < i1) THEN
                IF (sharedReal8(threadID + i1) > sharedReal8(threadID)) THEN
                    sharedReal8(threadID) = sharedReal8(threadID + i1)
                END IF
            END IF
            i1 = ishft(i1,-1)
        END DO

        CALL syncthreads()

        IF (threadID .EQ. 0) THEN
            IF (sharedReal8(0) > reduction_res(1)) THEN
                reduction_res(1) = sharedReal8(0)
            END IF
        END IF

        CALL syncthreads()

    END SUBROUTINE cuda_reduction_max

    ATTRIBUTES (GLOBAL) SUBROUTINE jacobi_device(A,Anew,imax,jmax,reduction_array)
        REAL(KIND=8), DEVICE, DIMENSION(*) :: A, Anew
        INTEGER(KIND=4), VALUE :: imax, jmax
        REAL(KIND=8), DEVICE, DIMENSION(*) :: reduction_array
        REAL(KIND=8), DIMENSION(0:*), SHARED :: sharedMem

        REAL(KIND=8) :: error_tlocal
        INTEGER(KIND=4) :: i, j

        j = blockDim%y * (blockIdx%y-1) + threadIdx%y
        i = blockDim%x * (blockIdx%x-1) + threadIdx%x

        error_tlocal = -1.0_8*HUGE(error_tlocal)

        IF(i >= 2 .and. i<= imax+1 .and. j >= 2 .and. j <= jmax+1) THEN
             Anew((j-1)*(imax+2) + i) = 0.25_8 * ( A((j  )*(imax+2) + i)   + A((j-2)*(imax+2) + i  ) + &
                                                      A((j-1)*(imax+2) + i-1) + A((j-1)*(imax+2) + i+1) )
             error_tlocal = max( error_tlocal, abs(Anew((j-1)*(imax+2) + i)-A((j-1)*(imax+2) + i)) )
        END IF

        CALL cuda_reduction_max(sharedMem, reduction_array((blockIdx%z - 1)*gridDim%y*gridDim%x + (blockIdx%y - 1)*gridDim%x + (blockIdx%x - 1) + 1:), error_tlocal)

    END SUBROUTINE jacobi_device

    SUBROUTINE jacobi_host(A,Anew,error,imax,jmax,h_reduction_array,d_reduction_array,nshared,maxblocks,grid,tblock)
        REAL(KIND=8), DEVICE, DIMENSION(*) :: A, Anew
        REAL(KIND=8) :: error
        INTEGER(KIND=4) :: imax,jmax 

        INTEGER(KIND=4) :: nshared,maxblocks
        REAL(KIND=8), DIMENSION(maxblocks) :: h_reduction_array
        REAL(KIND=8), DEVICE, DIMENSION(maxblocks) :: d_reduction_array

    
        TYPE(dim3) :: grid,tblock

        INTEGER(KIND=4) :: iblock
        
        DO iblock = 1, maxblocks
            h_reduction_array(iblock) = -1.0*HUGE(error)
        END DO
!   copy from host to device
        d_reduction_array = h_reduction_array(1:maxblocks)

        CALL jacobi_device<<<grid,tblock,nshared>>>(A,Anew,imax,jmax,d_reduction_array)

!   copy from device to host
        h_reduction_array(1:maxblocks) = d_reduction_array

        DO iblock = 1, maxblocks
            error = MAX(error, h_reduction_array(iblock))
        END DO

    END SUBROUTINE jacobi_host

    ATTRIBUTES (GLOBAL) SUBROUTINE copy(A,Anew,imax,jmax)
        REAL(KIND=8), DEVICE, DIMENSION(*) :: A, Anew
        INTEGER(KIND=4), VALUE :: imax, jmax

        INTEGER(KIND=4) :: i, j

        j = blockDim%y * (blockIdx%y-1) + threadIdx%y
        i = blockDim%x * (blockIdx%x-1) + threadIdx%x

        IF(i >= 2 .and. i<= imax+1 .and. j >= 2 .and. j <= jmax+1) THEN
            A((j-1)*(imax+2) + i) = Anew((j-1)*(imax+2) + i)
        END IF

    END SUBROUTINE copy

END MODULE CUDA_KERNELS
